#%RAML 1.0 Trait

headers:
      transactionId:
        description: This field defines trnsaction ID
        type: string
        required: true
        minLength: 30
        maxLength: 36
      clientId:
        description: This field defines clientId ID
        type: string
        required: true
        minLength: 30
        maxLength: 36
      clientSecret:
        description: This field defines clientSecret
        type: string
        required: true
        minLength: 30
        maxLength: 36     
    